import type { SourceResult } from "../sourcing/candidate-mappers";
import { dedupeCandidates } from "../rules";
import { scoreCandidate } from "../scoring";
import type { ApifyProfile } from "../sourcing/apify";
import type { SillageProfile } from "../sourcing/sillage";
import type { WebSearchPlatform } from "../sourcing/web-leads";
import type { Campaign, Candidate, ScoringWeights } from "../types";
import { genId, initialsFrom } from "../utils";

/**
 * Base query text for a web-search-sourced platform, built from the campaign's
 * existing sourcing strategy (no new query-building system — reuses the boolean/
 * tag strings already generated by buildSourcingStrategy). The route scopes this
 * with `site:` per platform.
 */
export function baseWebQuery(campaign: Campaign, platform: WebSearchPlatform): string {
  const jd = campaign.jobAnalysis;
  if (platform === "LinkedIn") return campaign.sourcingStrategy.linkedinBoolean;
  if (platform === "Stack Overflow") {
    const tags = campaign.sourcingStrategy.stackOverflowTags;
    return tags.length ? tags.map((t) => `"${t}"`).join(" OR ") : jd.title;
  }
  // Dribbble / Behance are portfolio platforms — a boolean recruiter string
  // doesn't fit; title + top skill is what a human would actually search.
  return [jd.title, jd.requiredSkills[0] ?? ""].filter(Boolean).join(" ");
}

/**
 * Parse the "Source via Sillage" dialog's single free-text field into the
 * identifier shape /api/source/sillage/start expects — a linkedin.com URL is
 * sent as linkedinUrl, anything else as a bare domain (protocol/www/path
 * stripped if the operator pasted a full URL).
 */
export function parseSillageIdentifier(input: string): { domain?: string; linkedinUrl?: string } {
  const trimmed = input.trim();
  if (/linkedin\.com\//i.test(trimmed)) {
    return { linkedinUrl: /^https?:\/\//i.test(trimmed) ? trimmed : `https://${trimmed}` };
  }
  return { domain: trimmed.replace(/^https?:\/\//i, "").replace(/^www\./i, "").split("/")[0] };
}

/**
 * Map real Sillage account-mapping profiles into scored, deduped Candidates —
 * the live counterpart to mapGithubCandidates/mapWebSearchCandidates,
 * same scoring + dedupe pipeline, real data. Kept here rather than mock-ai.ts
 * because it needs the campaign's live effective weights, which only exist in
 * this client-side store — /api/source/sillage/status has no access to campaign
 * state and returns raw profiles only.
 */
export function mapSillageCandidates(
  profiles: SillageProfile[],
  campaign: Campaign,
  companyLabel: string,
  existing: Candidate[],
  weights: ScoringWeights = campaign.scoringWeights,
): SourceResult {
  const jd = campaign.jobAnalysis;
  const allSkills = [...jd.requiredSkills, ...jd.niceToHaveSkills];
  const raw: Candidate[] = profiles.map((p) => {
    const name = [p.firstName, p.lastName].filter(Boolean).join(" ").trim() || "Unknown";
    const headline = (p.headline ?? "").trim();
    const about = (p.about ?? "").trim();
    const hay = `${p.position ?? ""} ${headline} ${about}`.toLowerCase();
    const techStack = allSkills.filter((s) => hay.includes(s.toLowerCase()));
    const location = [p.location?.city, p.location?.region, p.location?.country].filter(Boolean).join(", ");
    return {
      id: genId("cand"),
      campaignId: campaign.id,
      name,
      email: p.email ?? "",
      phone: p.phone ?? undefined,
      avatarInitials: initialsFrom(name),
      currentTitle: p.position || "",
      currentCompany: companyLabel,
      location,
      timezone: "",
      linkedinUrl: p.linkedinUrl ?? "",
      githubUrl: "",
      sourcePlatform: "Sillage",
      sourceQuery: companyLabel,
      matchScore: 0,
      matchBreakdown: [],
      techStack,
      yearsExperience: null,
      companyStageExperience: [],
      industryExperience: [],
      recentActivity: headline || about.slice(0, 140) || `Sourced via Sillage account mapping: ${companyLabel}.`,
      stage: "Sourced",
      lastContactedAt: null,
      outreachHistory: [],
      replyHistory: [],
      booking: null,
      complianceFlags: {
        doNotContact: false,
        suppressed: false,
        unsubscribed: false,
        gdprExportRequested: false,
        anonymized: false,
        suppressedUntil: null,
      },
      createdAt: new Date().toISOString(),
      provenance: "live",
    };
  });

  const { accepted, skipped } = dedupeCandidates(raw, existing, {
    excludedCompanies: campaign.sourcingStrategy.excludedCompanies,
  });
  const scored = accepted.map((c) => {
    const { score, breakdown } = scoreCandidate(c, jd, weights);
    return { ...c, matchScore: score, matchBreakdown: breakdown };
  });
  return { accepted: scored, skipped };
}

/**
 * Map real Apify (harvestapi/linkedin-profile-search) profiles into scored,
 * deduped Candidates — same scoring + dedupe pipeline as mapSillageCandidates,
 * real data. This is third-party public-profile data bought from a vendor API,
 * not a first-party LinkedIn scrape (see sourcing/apify.ts's header comment
 * and linkedin-policy.ts): every candidate is stamped with a recruiter-facing
 * note recording that provenance and that lawful-basis/consent review under
 * GDPR is the recruiter's responsibility before outreach.
 */
export function mapApifyCandidates(
  profiles: ApifyProfile[],
  campaign: Campaign,
  query: string,
  existing: Candidate[],
  weights: ScoringWeights = campaign.scoringWeights,
): SourceResult {
  const jd = campaign.jobAnalysis;
  const allSkills = [...jd.requiredSkills, ...jd.niceToHaveSkills];
  const raw: Candidate[] = profiles.map((p) => {
    const name = [p.firstName, p.lastName].filter(Boolean).join(" ").trim() || "Unknown";
    const headline = p.headline.trim();
    const about = p.about.trim();
    const hay = `${headline} ${about} ${p.topSkills.join(" ")} ${p.skills.join(" ")}`.toLowerCase();
    const techStack = allSkills.filter((s) => hay.includes(s.toLowerCase()));
    const currentCompany = p.currentPosition[0]?.companyName ?? "";
    return {
      id: genId("cand"),
      campaignId: campaign.id,
      name,
      email: p.email ?? "",
      avatarInitials: initialsFrom(name),
      currentTitle: headline || jd.title,
      currentCompany,
      location: p.location?.text ?? "",
      timezone: "",
      linkedinUrl: p.linkedinUrl,
      githubUrl: "",
      sourceExternalId: p.publicIdentifier || p.id || undefined,
      sourcePlatform: "Apify",
      sourceQuery: query,
      matchScore: 0,
      matchBreakdown: [],
      techStack,
      yearsExperience: jd.minYearsExperience ?? (jd.seniority === "Senior" ? 6 : 4),
      companyStageExperience: [],
      industryExperience: [],
      recentActivity: headline || about.slice(0, 140) || "Sourced via Apify LinkedIn profile search.",
      stage: "Sourced",
      lastContactedAt: null,
      outreachHistory: [],
      replyHistory: [],
      booking: null,
      complianceFlags: {
        doNotContact: false,
        suppressed: false,
        unsubscribed: false,
        gdprExportRequested: false,
        anonymized: false,
        suppressedUntil: null,
      },
      createdAt: new Date().toISOString(),
      provenance: "live",
      notes: [
        {
          id: genId("note"),
          text:
            "Sourced via Apify (harvestapi/linkedin-profile-search) — third-party public LinkedIn profile data. " +
            "Lawful-basis/consent review under GDPR is the recruiter's responsibility before outreach.",
          at: new Date().toISOString(),
        },
      ],
    };
  });

  const { accepted, skipped } = dedupeCandidates(raw, existing, {
    excludedCompanies: campaign.sourcingStrategy.excludedCompanies,
  });
  const scored = accepted.map((c) => {
    const { score, breakdown } = scoreCandidate(c, jd, weights);
    return { ...c, matchScore: score, matchBreakdown: breakdown };
  });
  return { accepted: scored, skipped };
}
