#!/bin/sh
set -eu

export DEERFLOW_MODEL_API_KEY="$(tr -d '\r\n' < "${DEERFLOW_MODEL_API_KEY_FILE:?DEERFLOW_MODEL_API_KEY_FILE is required}")"
export DEER_FLOW_INTERNAL_AUTH_TOKEN="$(tr -d '\r\n' < "${DEER_FLOW_INTERNAL_AUTH_TOKEN_FILE:?DEER_FLOW_INTERNAL_AUTH_TOKEN_FILE is required}")"
unset DATABASE_URL DEERFLOW_DATABASE_URL DEERFLOW_DATABASE_HOST DEERFLOW_DATABASE_PASSWORD \
  DEERFLOW_DATABASE_PASSWORD_FILE DEER_FLOW_STREAM_BRIDGE_REDIS_URL \
  DEERFLOW_STREAM_BRIDGE_REDIS_URL DEERFLOW_STREAM_BRIDGE_REDIS_HOST REDIS_URL \
  DEERFLOW_REDIS_PASSWORD DEERFLOW_REDIS_PASSWORD_FILE ARIA_DB_PASSWORD_B64 \
  ARIA_REDIS_PASSWORD_B64 LANGSMITH_API_KEY LANGCHAIN_API_KEY LANGFUSE_PUBLIC_KEY \
  LANGFUSE_SECRET_KEY LANGFUSE_BASE_URL MONOCLE_EXPORTERS OKAHU_API_KEY
export LANGSMITH_TRACING=false
export LANGCHAIN_TRACING_V2=false
export LANGCHAIN_TRACING=false
export LANGFUSE_TRACING=false
export MONOCLE_TRACING=false

cd /app/backend
exec env PYTHONPATH=. uv run --no-sync uvicorn aria_deerflow_app:app \
  --host "${DEERFLOW_BIND_HOST:?DEERFLOW_BIND_HOST is required}" --port 8001 --workers 1
