#!/bin/sh
set -eu

read_secret() {
  tr -d '\r\n' < "$1"
}

export DATABASE_PASSWORD="$(read_secret "${FLOWISE_DATABASE_PASSWORD_FILE:?FLOWISE_DATABASE_PASSWORD_FILE is required}")"
export REDIS_PASSWORD="$(read_secret "${FLOWISE_REDIS_PASSWORD_FILE:?FLOWISE_REDIS_PASSWORD_FILE is required}")"
export FLOWISE_SECRETKEY_OVERWRITE="$(read_secret "${FLOWISE_ENCRYPTION_KEY_FILE:?FLOWISE_ENCRYPTION_KEY_FILE is required}")"
export JWT_AUTH_TOKEN_SECRET="$(read_secret "${FLOWISE_JWT_AUTH_SECRET_FILE:?FLOWISE_JWT_AUTH_SECRET_FILE is required}")"
export JWT_REFRESH_TOKEN_SECRET="$(read_secret "${FLOWISE_JWT_REFRESH_SECRET_FILE:?FLOWISE_JWT_REFRESH_SECRET_FILE is required}")"
export EXPRESS_SESSION_SECRET="$(read_secret "${FLOWISE_SESSION_SECRET_FILE:?FLOWISE_SESSION_SECRET_FILE is required}")"
export TOKEN_HASH_SECRET="$(read_secret "${FLOWISE_TOKEN_HASH_SECRET_FILE:?FLOWISE_TOKEN_HASH_SECRET_FILE is required}")"

exec "$@"
