#!/usr/bin/env bash
# Shared Graph delegated permissions for Mantu Fly (Outlook mail/calendar + SSO).
# Includes Mail.Read, Mail.Send, Calendars.ReadWrite (delegated scopes).
apply_mantu_graph_delegated_permissions() {
  local app_id="$1"
  local graph_api="00000003-0000-0000-c000-000000000000"
  local perm_ids=(
    "37f7f235-527c-4136-accd-4a02d197975b=Scope"
    "64a6cdd6-aab1-4aaf-94b8-3cc8405e90d0=Scope"
    "14dad69e-099b-42c9-810b-d002981feec1=Scope"
    "7427e0e9-2fdb-4417-809c-591378161370=Scope"
    "e1fe6dd8-ba31-4d61-89e7-88639da4683d=Scope"
    "570282fd-fa5c-430d-a7fd-fc8dc98a9dca=Scope"
    "e383f46e-2787-4529-855e-0e479a3ffac0=Scope"
    "1ec239c2-d7c9-4623-a91a-a9775856bb36=Scope"
    "a65f2972-a4f8-4f5e-afd7-69ccb046d5dc=Scope"
  )
  echo "Ensuring Graph delegated permissions on appId=$app_id…"
  az ad app permission add --id "$app_id" --api "$graph_api" \
    --api-permissions "${perm_ids[@]}" >/dev/null 2>&1 || true
  if az ad app permission admin-consent --id "$app_id" >/dev/null 2>&1; then
    echo "Admin consent granted."
  else
    echo "WARN: admin-consent failed — grant in Azure Portal → API permissions."
  fi
  az ad sp create --id "$app_id" >/dev/null 2>&1 || true
}

write_owner_microsoft_env() {
  local out="$1" tenant_id="$2" account_upn="$3" app_id="$4" client_secret="$5" app_redirect="$6"
  umask 077
  cat > "$out" <<EOF
# Generated by ARIA Mantu Graph setup — NEVER commit
# tenant=$tenant_id account=$account_upn created=$(date -u +%Y-%m-%dT%H:%MZ)
MICROSOFT_CLIENT_ID=$app_id
MICROSOFT_CLIENT_SECRET=$client_secret
MICROSOFT_REDIRECT_URI=$app_redirect
MICROSOFT_TENANT_ID=$tenant_id
GOTRUE_EXTERNAL_AZURE_ENABLED=true
GOTRUE_EXTERNAL_AZURE_CLIENT_ID=$app_id
GOTRUE_EXTERNAL_AZURE_SECRET=$client_secret
GOTRUE_EXTERNAL_AZURE_URL=https://login.microsoftonline.com/${tenant_id}/v2.0
EOF
  chmod 600 "$out"
}
