#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# Bring up LOCAL Supabase, apply every numbered migration (including RLS, delivery,
# approval lifecycle, and unsubscribe policy),
# and write .env.local so the Hermes app runs in LIVE mode against the local stack.
#
# Prereq: Docker Desktop running (open it once + accept first-launch onboarding).
# Run once:  bash scripts/local-supabase-up.sh   then  npm run dev
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail
cd "$(dirname "$0")/.."

SB="./.localbin/supabase"; [ -x "$SB" ] || SB="supabase"

if ! docker info >/dev/null 2>&1; then
  echo "✗ Docker is not running. Open Docker Desktop, accept the first-launch onboarding,"
  echo "  wait until it says 'Engine running', then re-run this script."
  exit 1
fi

[ -f supabase/config.toml ] || { echo "▸ supabase init"; "$SB" init; }

echo "▸ Starting local Supabase (first run pulls container images — a few minutes)…"
"$SB" start

echo "▸ Applying every numbered migration via db reset…"
"$SB" db reset

echo "▸ Capturing local keys → .env.local"
ENV_OUT="$("$SB" status -o env 2>/dev/null || true)"
URL="$(printf '%s\n' "$ENV_OUT"   | grep -E '^API_URL='          | cut -d= -f2- | tr -d '"')"
ANON="$(printf '%s\n' "$ENV_OUT"  | grep -E '^ANON_KEY='         | cut -d= -f2- | tr -d '"')"
SROLE="$(printf '%s\n' "$ENV_OUT" | grep -E '^SERVICE_ROLE_KEY=' | cut -d= -f2- | tr -d '"')"
cat > .env.local <<EOF
# Local Supabase — generated by scripts/local-supabase-up.sh ($(date -u +%Y-%m-%dT%H:%M:%SZ))
NEXT_PUBLIC_SUPABASE_URL=${URL:-http://127.0.0.1:54321}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON}
SUPABASE_SERVICE_ROLE_KEY=${SROLE}
EOF

echo "✓ Local Supabase up + migrations applied. Restart 'npm run dev' to pick up .env.local."
echo "  Studio:  http://127.0.0.1:54323"
echo "  DB:      postgresql://postgres:postgres@127.0.0.1:54322/postgres"
